# Generated by Django 5.2.3 on 2025-09-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking_reference',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.booking'),
        ),
    ]
